// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuky7ErPnO1A42B6lVphyQModu2EgtrZY',
    appId: '1:700437646605:web:4104543de08768eeacf444',
    messagingSenderId: '700437646605',
    projectId: 'pilgramz-test-mode',
    authDomain: 'pilgramz-test-mode.firebaseapp.com',
    storageBucket: 'pilgramz-test-mode.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDV2DlkcA9P47_2cf2gw9j9ntMZXfotJTU',
    appId: '1:700437646605:android:a181bce8e9ef74afacf444',
    messagingSenderId: '700437646605',
    projectId: 'pilgramz-test-mode',
    storageBucket: 'pilgramz-test-mode.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDei6gDaavCRo72YlRjHlh9Xm_N4SkwUk',
    appId: '1:700437646605:ios:ab4ca0fbc76a51ddacf444',
    messagingSenderId: '700437646605',
    projectId: 'pilgramz-test-mode',
    storageBucket: 'pilgramz-test-mode.appspot.com',
    iosClientId:
        '700437646605-pl99oighq6dls58dm6h8gnars1d5hqk6.apps.googleusercontent.com',
    iosBundleId: 'dev.navod.flutter.pilgramz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDei6gDaavCRo72YlRjHlh9Xm_N4SkwUk',
    appId: '1:700437646605:ios:ab4ca0fbc76a51ddacf444',
    messagingSenderId: '700437646605',
    projectId: 'pilgramz-test-mode',
    storageBucket: 'pilgramz-test-mode.appspot.com',
    iosClientId:
        '700437646605-pl99oighq6dls58dm6h8gnars1d5hqk6.apps.googleusercontent.com',
    iosBundleId: 'dev.navod.flutter.pilgramz',
  );
}
